# Generated by Django 5.0.4 on 2024-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CU', 'Customer'), ('MF', 'Manufacture'), ('WH', 'Warehouse'), ('SA', 'Sales'), ('MS', 'Supply')], default='CU', max_length=2),
        ),
    ]
