# Generated by Django 5.0.4 on 2024-05-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
    ]
